### ISSUE TITLE
no bias in mlp.py

### ISSUE THREAD

**Issue by rasmuspjohansson** [mdenil/dropout#1]
Great initiative to implement the dropout technique in theano! But is there any reason why the mpl.py code doesnt use bias for its neurons?

**Comment by mdenil** [comment]
Looks like an oversight on my part, I've pushed a fix that re-enables them.  Thanks for noticing!

**Comment by mdenil** [comment]
Looking at this again we actually get better performance on MNIST without the biases (which is likely why I'd removed them in the first place).  Instead of being disabled entirely I've made them optional in 608f276411ec35abc4d30bc2aaa65845ab7398a4
